apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-tower-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spire.labels" . | nindent 4 }}
data:
  tower.json: |
    {
      "name": {{ .Values.tower.name | quote }},
      "max_concurrent": {{ .Values.tower.maxConcurrent }},
      "deployment_mode": "cluster-native"
    }
