{{- if .Values.dolthub.credsKeyId }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-dolthub-creds
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  key-id: {{ .Values.dolthub.credsKeyId | b64enc | quote }}
  key-value: {{ .Values.dolthub.credsKeyValue | b64enc | quote }}
{{- end }}
